// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	CreateTaskRequest
	CreateTaskResponse
	Task
	TaskParams
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type CreateTaskRequest struct {
	Task *TaskParams `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *CreateTaskRequest) Reset()                    { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()               {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateTaskRequest) GetTask() *TaskParams {
	if m != nil {
		return m.Task
	}
	return nil
}

// The response message containing the greetings
type CreateTaskResponse struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *CreateTaskResponse) Reset()                    { *m = CreateTaskResponse{} }
func (m *CreateTaskResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTaskResponse) ProtoMessage()               {}
func (*CreateTaskResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateTaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type Task struct {
	Id     string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Params *TaskParams `protobuf:"bytes,2,opt,name=params" json:"params,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Task) GetParams() *TaskParams {
	if m != nil {
		return m.Params
	}
	return nil
}

type TaskParams struct {
	Url      string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	StartAt  uint64 `protobuf:"varint,2,opt,name=start_at,json=startAt" json:"start_at,omitempty"`
	Interval uint64 `protobuf:"varint,3,opt,name=interval" json:"interval,omitempty"`
}

func (m *TaskParams) Reset()                    { *m = TaskParams{} }
func (m *TaskParams) String() string            { return proto.CompactTextString(m) }
func (*TaskParams) ProtoMessage()               {}
func (*TaskParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*CreateTaskRequest)(nil), "service.CreateTaskRequest")
	proto.RegisterType((*CreateTaskResponse)(nil), "service.CreateTaskResponse")
	proto.RegisterType((*Task)(nil), "service.Task")
	proto.RegisterType((*TaskParams)(nil), "service.TaskParams")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ScrapeService service

type ScrapeServiceClient interface {
	// Sends a greeting
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
}

type scrapeServiceClient struct {
	cc *grpc.ClientConn
}

func NewScrapeServiceClient(cc *grpc.ClientConn) ScrapeServiceClient {
	return &scrapeServiceClient{cc}
}

func (c *scrapeServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	out := new(CreateTaskResponse)
	err := grpc.Invoke(ctx, "/service.ScrapeService/CreateTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ScrapeService service

type ScrapeServiceServer interface {
	// Sends a greeting
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
}

func RegisterScrapeServiceServer(s *grpc.Server, srv ScrapeServiceServer) {
	s.RegisterService(&_ScrapeService_serviceDesc, srv)
}

func _ScrapeService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapeServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ScrapeService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapeServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ScrapeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.ScrapeService",
	HandlerType: (*ScrapeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _ScrapeService_CreateTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x50, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0xa5, 0x6d, 0xd4, 0x96, 0x43, 0x41, 0x70, 0x2c, 0x21, 0x2c, 0xe0, 0x05, 0x24, 0xa4, 0x0e,
	0x65, 0x60, 0x61, 0x41, 0x1d, 0x58, 0x91, 0x0b, 0x12, 0x1b, 0x3a, 0xc2, 0x0d, 0x11, 0x21, 0x31,
	0xf6, 0x85, 0xdf, 0x4f, 0xe2, 0x98, 0x84, 0x08, 0xd8, 0xee, 0xf9, 0xde, 0x87, 0xef, 0x41, 0xec,
	0xd8, 0x7e, 0xe6, 0x19, 0xaf, 0x8c, 0xad, 0xa4, 0xc2, 0x45, 0x80, 0xea, 0x06, 0x0e, 0x37, 0x96,
	0x49, 0xf8, 0x81, 0xdc, 0x9b, 0xe6, 0x8f, 0x9a, 0x9d, 0xe0, 0x39, 0x44, 0xd2, 0xc0, 0x64, 0x72,
	0x3a, 0xb9, 0xd8, 0x5b, 0x1f, 0xad, 0xbe, 0xb5, 0x2d, 0xe7, 0x9e, 0x2c, 0xbd, 0x3b, 0xed, 0x09,
	0xea, 0x1a, 0xf0, 0xa7, 0xda, 0x99, 0xaa, 0x74, 0x8c, 0x67, 0x23, 0x79, 0x3c, 0x92, 0x07, 0xe1,
	0x06, 0xa2, 0x16, 0xe1, 0x3e, 0x4c, 0xf3, 0x57, 0x4f, 0xdc, 0xd5, 0xcd, 0x84, 0x97, 0x30, 0x37,
	0x3e, 0x20, 0x99, 0xfe, 0x9f, 0x1d, 0x28, 0xea, 0x11, 0x60, 0x78, 0xc5, 0x03, 0x98, 0xd5, 0xb6,
	0x08, 0x5e, 0xed, 0x88, 0xc7, 0xb0, 0x74, 0x42, 0x56, 0x9e, 0x49, 0xbc, 0x5d, 0xa4, 0x17, 0x1e,
	0xdf, 0x0a, 0xa6, 0xb0, 0xcc, 0x4b, 0x69, 0xac, 0xa9, 0x48, 0x66, 0x7e, 0xd5, 0xe3, 0xf5, 0x13,
	0xc4, 0xdb, 0xcc, 0x92, 0xe1, 0x6d, 0x17, 0x8d, 0x77, 0x00, 0xc3, 0x95, 0x98, 0xf6, 0x5f, 0xfa,
	0x55, 0x5c, 0x7a, 0xf2, 0xe7, 0xae, 0xab, 0x45, 0xed, 0xbc, 0xcc, 0x7d, 0xf9, 0x57, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xba, 0x89, 0x09, 0x3a, 0x8d, 0x01, 0x00, 0x00,
}
